### PR TITLE
Consider switching to easyfft

### PR DESCRIPTION
**Pull request by WalterSmuts**
[easyfftt](https://docs.rs/easyfft/latest/easyfft/) makes the logic simpler and gets rid of the planner struct.

If you're good with the idea, I'd be happy to convert the rest of the plugin examples.

Please let me know what you think.

### CODE REVIEW

**Comment by robbert-vdh** [comment]
Thanks for the PR. Sadly, I cannot accept this. These changes don't make the code much simpler (and certainly not any simpler than a helper function would) while adding another layer of dependencies and also introducing an unnecessary source of realtime unsafeness by using thread locals. With realtime audio you want to avoid allocating and deallocating on audio threads as much as possible, and your PR moves allocations from init time to the audio thread. And any time the host calls the process function from a different audio thread you would now need to repeat those allocations.

**Comment by WalterSmuts** [comment]
> These changes don't make the code much simpler (and certainly not any simpler than a helper function would)

The main advantage is not having to manage the planner struct. A simple helper function wouldn't be able to get rid of that. A more complicated one would, but you'd essentially be re-writing `easyfft`. My main reason for creating `easyfft` was the observation that a DFT is a pure function, from a mathematical point of view, that shouldn't have any state involved. `easyfft` just tries to reflect that fact in the API.

`easyfft` also tries to limit all the ways the user can cut themselves. Removing the planner removes sources of error. The user now can not specify a planner with a size that doesn't correspond to the size of their buffer. Notice the lack of `unwrap()`. That's simply because you cannot fail when attempting to process an `fft` or `ifft`. Along with managing the planner `easyfft` also manages the scratch buffers. Your current code is actually pretty fragile. Currently you don't need a scratch buffer with your specific `FFT_SIZE`. You've passed `&[]` for this buffer. This may change if you want to change `FFT_SIZE`. It may change on different architectures. Hell, it may even change on a patch update of `rustfft`. If any of these things change, it'll break your code.

> With realtime audio you want to avoid allocating and deallocating on audio threads as much as possible, and your PR moves allocations from init time to the audio thread. And any time the host calls the process function from a different audio thread you would now need to repeat those allocations.

I 100% agree. My understanding is that there little difference between initialising at the "start" and initialising on the first fft call. If this is not true, I may need a `warm_fft_cache(FFT_SIZE)` function to allow the user to move initialisation earlier. As for switching between threads? Why would the host do this? AFAIK there are many other similar reasons for not wanting to switch the thread doing the audio processing. Cache-locality and simply spawning new threads are expensive generally. The underlying data-structure (generic_singleton) I use has the ability to allocate a global version but there's trade-offs with synchronisation around access if we move to this. My understanding thus far is that a thread_local version is better.

Please let me know if you have any proposals for changes to `easyfft` that would make you consider switching to it.

**Comment by robbert-vdh** [comment]
I wasn't going to respond but I felt obliged to just point a couple things out:

> Notice the lack of unwrap(). That's simply because you cannot fail when attempting to process an fft or ifft.

I'm not sure if that's a good thing. One of the reasons why an IFFT would fail is because the first or last bin's value contains an imaginary component. This is a bug in the program, and silently getting rid of the error without informing the caller simply obfuscates the error.

> My understanding is that there little difference between initialising at the "start" and initialising on the first fft call.

There is. Audio plugins (like in this repo) revolve around realtime audio process. If there's any way you can avoid locking, (de)allocating, making syscalls, and performing any other potentially blocking operation from an audio thread you should. Your approach involves two of those things, which makes it unsuitable for realtime use.

> As for switching between threads? Why would the host do this?

Because they use a work stealing job scheduler. If you have five parallel tracks that need processing and only four cores to work with, then whichever core finishes processing a track first gets to process the fifth track.

> Please let me know if you have any proposals for changes to easyfft that would make you consider switching to it.

I'm not going to add another dependency for a wrapper I could trivially write myself, so it would need to be included in realfft. And it would also need to be able to use preallocated structs instead ofo relying on TLS.

**Comment by WalterSmuts** [comment]
> I wasn't going to respond but I felt obliged to just point a couple things out.

I'm happy you did. I really appreciate feedback to improve my projects. It's very valuable.

> One of the reasons why an IFFT would fail is because the first or last bin's value contains an imaginary component. This is a bug in the program, and silently getting rid of the error without informing the caller simply obfuscates the error.

I'm glad you pointed this out :) I 100% agree. `easyfft` is designed so you can't ever hit this bug. The user cannot set the first bin to a complex value. So regardless of what you do, you cannot cut yourself like that. Try it ;)

> I'm not going to add another dependency for a wrapper I could trivially write myself

I think you might be underestimating the subtlety in the design and the amount of work that goes into the implementation of that design. But even simple ideas merit being factored into a separate crate so others don't have to re-implement the same thing each time. Consider `Option`, a relatively simple data-structure. I'm sure you *can* roll your own, but you don't have to and I'd argue your time is better spent not to.

> so it would need to be included in realfft

I originally thought so too. But over some time enough complexity built up in `easyfftt` that I now think it merits being in a separate crate. Same reason why `rustfft` and `realfft` are in separate crates. It's a trade-off that gradually favours creating a new crate as the complexity of the new crate increases and a "separation of concerns" boundary develops. I think `easyfft` has crossed that threshold but I'm sure there are good arguments for both views. Either way, I don't see that much of a practical difference if the code is contained in a separate crate or not for the end-user.

>There is. Audio plugins (like in this repo) revolve around realtime audio process. If there's any way you can avoid locking, (de)allocating, making syscalls, and performing any other potentially blocking operation from an audio thread you should. Your approach involves two of those things, which makes it unsuitable for realtime use.

Interesting. AFAICT `easyfft ` would only possibly allocate during the first iteration of a `process` call. What's the other blocking operation you're referring to?

My gut feel says it won't be an issue in practice because it only happens once on the first call for each thread. A thread pool should warm up quickly too. I suspect the variation in latency between one of these "first" process calls would be of the same order of magnitude you can expect from other non-deterministic operations on a modern OS. E.g. scheduler latency or caches warming up or so.

But from an academic point of view I'm curious. Let's say the first call to process takes significantly longer than the rest. Let's say 10 seconds... What happens then? Will VST3 or CLAP just drop the intermediate samples? Will a 10 second delay build up? Will some other component panic? I feel if the intermediate samples get dropped, then it's probably okay right?

Am thinking of ways that you can warm the Planner cache on startup of new threads. Does CLAP or VST3 have an init hook for a thread right after creation but before accepting process requests?

**Pull request closed without merging**
